# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'difflog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for difflog
	pod 'SwiftUIWheelPicker'

  target 'difflogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'difflogUITests' do
    # Pods for testing
  end

end
